# Generated by Django 4.1.5 on 2023-02-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_qrcode_id_in_electron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='user',
        ),
    ]
