# Generated by Django 4.1.5 on 2023-02-26 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_qrcode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Жаңалық аты')),
                ('description', models.TextField(verbose_name='жаңалық тексті')),
                ('image', models.ImageField(upload_to='', verbose_name='Жаңалық фотосы')),
            ],
            options={
                'verbose_name': 'Жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='jk',
            options={'ordering': ['-id'], 'verbose_name': 'Тұрғын үй', 'verbose_name_plural': 'Тұрғын үй аты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name': 'Қолднушы', 'verbose_name_plural': 'Қолднушылар'},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-id'], 'verbose_name': 'электр есептегіш', 'verbose_name_plural': 'электр есептегіштер'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'қолданушы', 'verbose_name_plural': 'Қолданушылар'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='QrCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.qrcode', verbose_name='электр есептегіш'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Қолднушы'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='id_in_electron',
            field=models.IntegerField(unique=True, verbose_name='id есептегіш'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Qr код нәтижелері'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='электрондық пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='жүйеге администраторы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Тегі'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Әкесінің аты'),
        ),
    ]
