# Generated by Django 4.1.5 on 2023-02-26 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_news_alter_jk_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайктар'),
        ),
        migrations.AddField(
            model_name='news',
            name='value',
            field=models.CharField(choices=[('Like', True), ('Unlike', False)], default='Like', max_length=8, verbose_name='лайк статусы'),
        ),
    ]
